config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get 'signup/(:type)', to: 'user/registrations#new', as: 'signup'
  end

  devise_for :user, controllers: {registrations: 'user/registrations', sessions: 'user/sessions' },
             path_names: { edit: 'profile', sign_in: 'login', sign_out: 'logout' }

  get 'welcome/index'
  get 'search', to: 'welcome#search'
  get 'show_cities', to: 'welcome#show_cities'
  delete 'photos/:id', to: 'photos#destroy', as: 'photo'
  get 'register_pay' ,to: 'payments#create'

  resources :artists, param: :name, only: [:show, :destroy ] do
    resources :events do
      member do
        post 'add_event', to: 'fans#add_event', as: 'add'
        post 'remove_event', to: 'fans#remove_event', as: 'remove'
      end
    end
    member do
      post 'follow', to: 'fans#follow_artist'
      post 'unfollow', to: 'fans#unfollow_artist'
      get 'my_sales', to: 'artists#my_sales'
    end
    resources :products do
      member do
        post 'buy', to: 'orders#create'
      end
    end
  end

  resources :fans, only: [:show, :destroy] do
    member do
      get 'my_events'
      get 'followed_artists'
      get 'my_purchases', to: 'fan_purchases'
    end
  end

  root to: 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :authenticate_user!, except: [:index]
  before_action :search_params, only: [:search]

  # GET /
  def index
    @main_events = Audience.popular_events.collect! {|event| Event.find(event.first)}.to_enum
    @main_artists = Artist.all.sample(3).to_enum
  end

  # GET /search
  def search
    if params[:model].present?
      search_string = "%#{params[:model].html_safe}%"
      @artists = Artist.with_search_name(search_string)
      @events = Event.fields_with_input_string(search_string)
      @products = Product.with_search_title(search_string)
      @result = (@artists.to_a << @events.to_a << @products.to_a).flatten.collect do |result_elem|
        class_name = result_elem.class.to_s.downcase
        {'id': class_name + result_elem.id.to_s, name: result_elem.to_s, type: result_elem.class.to_s,
        url: result_elem.base_uri }
      end
    end
    if request.xml_http_request?
      respond_to do |format|
        format.json {
          render json: {result: @result}
        }
      end
    end
  end

  def show_cities
    if params[:state].present?
      @cities = CS.cities(params[:state].to_sym, :AR)
    end
    if request.xml_http_request?
      respond_to do |format|
        format.json {
          render json: {cities: @cities}
        }
      end
    end
  end

  private

  def search_params
    params.permit("model")
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <% @main_events.each.with_index do |event, i| %>
      <% if i.equal? 0 %>
        <div class="carousel-item active">
      <% else %>
        <div class="carousel-item">
      <% end %>
        <%= image_tag(event.photo.url) %>
        <div class="container">
          <div class="carousel-caption">
            <h1><%= event.title %></h1>
            <p><%= event.description %></p>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/welcome/_favourites_artists.html.erb
<div class="container marketing">
  <div class="row">
    <% loop do %>
      <div class="col-md-4 text-center">
        <% artist = @main_artists.next %>
        <%= image_tag(user_image_path(artist.user), size: '140x140' ,class: 'center-image rounded-circle') %>
        <h4><%= link_to artist.name, artist_path(artist.name) %></h4>
        <p><%= artist.description %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<%= render partial: 'welcome/carousel' %>
<%= render partial: 'welcome/favourites_artists' %>

app/views/welcome/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <% if @any_result %>
        <h2>Resultados de la b&uacutesqueda </h2>
      <% else %>
        <h2>Lo sentimos, no encontramos ning&uacuten resultado para <%= params[:model] %></h2>
      <% end %>

      <% if @artists.any? %>
        <div class="card">
          <div class="card-header">
            <%= icon('fas', 'users', 'Artistas') %>
          </div>
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <% @artists.each do |artist| %>
                <li class="list-group-item list-group-item-action">
                  <%= link_to artist.name, artist_path(artist) %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

      <% if @events.any? %>
        <div class="card">
          <div class="card-header">
            <%= icon('far', 'calendar-alt', 'Eventos') %>
          </div>
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <% @events.each do |event| %>
                <li class="list-group-item list-group-item-action">
                  <span class="date">
                    <div class="day"><%= l(event.start_date, format: '%d') %></div>
                    <div class="month"><%= l(event.start_date, format: '%b').upcase %></div>
                  </span>
                  <%= link_to event.title , artist_event_path(event.artist, event), class: 'event-title' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

      <% if @products.any? %>
        <div class="card">
          <div class="card-header">
            <%= icon('fas', 'compact-disc', 'Productos') %>
          </div>
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <% @products.each do |product| %>
                <li class="list-group-item list-group-item-action">
                  <div class="row">
                    <div class="col-md-1">
                      <%= image_tag(product.main_photo, size: '80x80') %>
                    </div>
                    <div class="col-md-3">
                      <%= link_to product.title, artist_product_path(product.artist.name, product), class: 'event-title' %>
                    </div>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>