config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get 'signup/(:type)', to: 'user/registrations#new', as: 'signup'
  end

  devise_for :user, controllers: {registrations: 'user/registrations', sessions: 'user/sessions' },
             path_names: { edit: 'profile', sign_in: 'login', sign_out: 'logout' }

  get 'welcome/index'
  get 'search', to: 'welcome#search'
  get 'show_cities', to: 'welcome#show_cities'
  delete 'photos/:id', to: 'photos#destroy', as: 'photo'
  get 'register_pay' ,to: 'payments#create'

  resources :artists, param: :name, only: [:show, :destroy ] do
    resources :events do
      member do
        post 'add_event', to: 'fans#add_event', as: 'add'
        post 'remove_event', to: 'fans#remove_event', as: 'remove'
      end
    end
    member do
      post 'follow', to: 'fans#follow_artist'
      post 'unfollow', to: 'fans#unfollow_artist'
      get 'my_sales', to: 'artists#my_sales'
    end
    resources :products do
      member do
        post 'buy', to: 'orders#create'
      end
    end
  end

  resources :fans, only: [:show, :destroy] do
    member do
      get 'my_events'
      get 'followed_artists'
      get 'my_purchases', to: 'fan_purchases'
    end
  end

  root to: 'welcome#index'
end

app/models/event.rb
class Event < ApplicationRecord

  include Rails.application.routes.url_helpers

  belongs_to :artist
  has_many :audiences
  has_many :fans, through: :audiences
  mount_uploader :photo, EventPhotoUploader

  validate :start_date_should_be_earlier_than_end_date
  validates_associated :artist
  validates :title, presence: true, length: { maximum: 40 }
  validates :start_date, presence: true
  validates :end_date, presence: true

  scope :fields_with_input_string, -> (input_string) {where ("title LIKE ? OR place LIKE ?"), input_string, input_string}
  scope :future_events, -> { where ("start_date > ?"), Time.zone.now }

  def to_s
    self.title
  end

  def base_uri
    artist_event_path(self.artist.name, self.id)
  end

  def start_date_should_be_earlier_than_end_date
    if end_date <= start_date
      errors.add(:end_date, "no puede ser anterior o igual a la fecha y hora de inicio")
    end
  end

  def finished?
    self.end_date < DateTime.current
  end

  def currently?
    DateTime.current.between?(self.start_date, self.end_date)
  end

  def audience_amount
    self.fans.size
  end

  def is_favourite_for?(aFan)
    self.fans.include? aFan
  end

  def how_much_time_is_left_to_start
    return "Evento finalizado" if self.finished?
    return "Evento en curso" if self.currently?
    how_much_time = ActiveSupport::Duration.build(self.start_date - DateTime.current)
    return create_string_response(how_much_time)
  end

  private

  def create_string_response(aDuration)
    string = "Faltan "
    traduction =  {:years => 'años', :months => 'meses', :weeks => 'semanas', :days => 'días', :hours => 'horas', :minutes => 'minutos'}
    aDuration.parts.delete(:seconds)
    aDuration.parts.each_pair do |unit_time, amount|
      string << "#{amount.to_s} " << "#{traduction[unit_time]}, "
      string.gsub!(traduction[unit_time],traduction[unit_time].singularize) if amount.equal? 1
    end
    string << "para el comienzo del evento"
    string.gsub!(/,\s(\d+)\s(\w+), para /) do |s|
      s.delete! ','
      s.prepend ' y'
      s.delete! ','
      p s
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!
  before_action :authenticate_artist! , except: [:show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_artist
  before_action :is_favourite?, only: [:show]


  # GET /artists/:artist_name/events
  def index
    @all_events = @artist.events
    @past_events = @all_events.select {|e| e.finished?}
    @next_events = @all_events - @past_events
  end

  # GET /artists/:artist_name/events/1
  def show
  end

  # GET /artists/:artist_name/events/new
  def new
    @event = Event.new
  end

  # GET artists/:artist_name/1/edit
  def edit
  end

  # POST /artists/:artist_name/events
  def create
    @event = Event.new(event_params)
    @event.artist = @artist
    respond_to do |format|
      if @event.save
        format.html { redirect_to artist_event_path(@artist, @event), notice: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /artists/:artist_name/events/1
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to artist_event_path(@artist, @event), notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /artists/:artist_name/events/1
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to artist_events_url(@artist), notice: 'Event was successfully destroyed.' }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :place, :start_date, :end_date, :photo)
    end

    def is_favourite?
      if current_user.fan?
        @is_favourite = current_user.profile.is_assistant_for? @event
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events_list.html.erb
<ul class="list-group">
  <% if @events.any? %>
    <% @events.each do |event| %>
      <li class="list-group-item justify-content-between">
        <div class="row">
          <div class="col-md-8">
            <span class="date">
                <div class="day"><%= l(event.start_date, format: '%d') %></div>
                <div class="month"><%= l(event.start_date, format: '%b ').upcase %></div>
              </span>
            <%= link_to event.title, artist_event_path(event.artist.name, event), class: 'event-title' %></div>
          <% if current_user.artist? %>
            <div class="col-md-2">
              <%= link_to(icon('far', 'edit', 'Editar'), edit_artist_event_path(@artist, event), class: 'btn btn-success') %>
            </div>
            <div class="col-md-2">
              <%= link_to(icon('far', 'trash-alt', 'Eliminar'), artist_event_path(@artist,event), method: :delete,
                          class: 'btn btn-danger', data: { confirm: "Estás seguro que quieres eliminar el evento #{event.title}?" }) %>
            </div>
          <% end %>
        </div>
      </li>
    <% end %>
  <% else %>
    <h3>Por el momento no hay eventos cargados</h3>
  <% end %>
</ul>

app/views/events/_events_nav.html.erb
<ul class="nav nav-tabs" id="event-tab" role="tablist">
    <li class="nav-item event-item">
        <a class="nav-link active" id="all-tab" data-toggle="tab" href="#all" role="tab" aria-controls="all" aria-selected="true">
          Todos
          <span class="badge badge-pill badge-primary"><%= @all_events.size %></span>
        </a>
    </li>
    <li class="nav-item event-item">
        <a class="nav-link" id="past-tab" data-toggle="tab" href="#past" role="tab" aria-controls="past" aria-selected="true">
          Pasados
          <span class="badge badge-pill badge-primary"><%= @past_events.size %></span>
        </a>
    </li>
    <li class="nav-item event-item">
        <a class="nav-link" id="next-tab" data-toggle="tab" href="#next" role="tab" aria-controls="next" aria-selected="true">
          Pr&oacuteximos
          <span class="badge badge-pill badge-primary"><%= @next_events.size %></span>
        </a>
    </li>
</ul>

<div class="tab-content" id="event-tab-content">
    <div class="tab-pane fade show active" id="all" role="tabpanel" aria-labelledby="all-tab">
        <%= @events = @all_events
        render 'events/events_list', locals: { events: @events }
        %>
    </div>
    <div class="tab-pane fade" id="past" role="tabpanel" aria-labelledby="past-tab">
        <%= @events = @past_events
        render 'events/events_list', locals: { events: @events }
        %>
    </div>
    <div class="tab-pane fade" id="next" role="tabpanel" aria-labelledby="next-tab">
        <%= @events = @next_events
        render 'events/events_list', locals: { events: @events }
        %>
    </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for([@artist,@event], defaults: { input_html: { class: 'form-control' }}) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= render 'layouts/form_aclaration' %>

  <div class="form-inputs">
    <%= f.input :title, required: true, autofocus: true, placeholder: 'Ingresá el título del evento', input_html: { maxlength: 40} %>
    <%= f.input :description, placeholder: 'Ingresá la información del evento para que sus seguidores puedan saber de que se trata!' %>
    <%= f.input :place, placeholder: 'Ingresá el lugar donde se desarrollará el evento', input_html: { maxlength: 50 } %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :photo, as: :file, hint: 'Seleccione una imágen para la portada del evento', input_html: { class: 'filestyle' } %>
  </div>

  <div class="form-actions">
    <%= f.submit @button_name, class: 'btn btn-success' %>
    <%= link_to 'Cancelar', artist_events_path(@artist, event), { class: 'btn btn-secondary', role: :button } %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">

      <h2>Editar evento</h2>
      <%= @button_name = 'Actualizar'
        render 'form', event: @event %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <h2>Mis eventos</h2>
      <%= link_to(icon('far', 'calendar-plus', 'Nuevo evento'), new_artist_event_path(@artist.name) , class: ['btn btn-success','new-button']) %>

      <%= render :partial => 'events_nav' %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">

      <h2>Crear evento</h2>
      <%= @button_name = 'Crear'
        render 'form', event: @event %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <% if current_user.fan? %>
            <% if @is_favourite %>
              <%= link_to(icon('fas','star'), remove_artist_event_path(@event), method: :post, id: 'remove-artist', title: 'Eliminar de favoritos') %>
            <% else %>
              <%= link_to(icon('far','star'), add_artist_event_path(@event), method: :post, id: 'add-artist', title: 'Agregar a favoritos') %>
            <% end %>
          <% end %>
        </div>
        <% if @event.photo.file.nil? %>
          <%= image_tag(@event.photo.url) %>
        <% else %>
          <%= image_tag(@event.photo.cover.url) %>
        <% end %>
        <div class="card-body">
          <h2 class="card-title"><%= @event.title %></h2>
          <h5>Organizado por <%= link_to @event.artist.name, artist_path(@event.artist) %></h5>
          <ul class="list-group list-group-flush">
            <li class="list-group-item list-group-item-action">
              <%= icon('fas','map-marker-alt') %>
              <span><%= @event.place %></span>
            </li>
            <li class="list-group-item list-group-item-action">
              <div>
                <%= icon('far', 'clock') %>
                <span><%= @event.start_date.strftime('%F %T') %> - <%= @event.end_date.strftime('%F %T') %></span>
              </div>
              <p><small><%= @event.how_much_time_is_left_to_start %></small></p>
            </li>
            <li class="list-group-item list-group-item-action">
              <%= icon('fas','info-circle') %>
              <span><%= @event.description %></span>
            </li>
            <li class="list-group-item list-group-item-action">
              <%= icon('fas', 'users') %>
              <span>A <%= @event.audience_amount.to_s %> personas les gusta este evento</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>