config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get 'signup/(:type)', to: 'user/registrations#new', as: 'signup'
  end

  devise_for :user, controllers: {registrations: 'user/registrations', sessions: 'user/sessions' },
             path_names: { edit: 'profile', sign_in: 'login', sign_out: 'logout' }

  get 'welcome/index'
  get 'search', to: 'welcome#search'
  get 'show_cities', to: 'welcome#show_cities'
  delete 'photos/:id', to: 'photos#destroy', as: 'photo'
  get 'register_pay' ,to: 'payments#create'

  resources :artists, param: :name, only: [:show, :destroy ] do
    resources :events do
      member do
        post 'add_event', to: 'fans#add_event', as: 'add'
        post 'remove_event', to: 'fans#remove_event', as: 'remove'
      end
    end
    member do
      post 'follow', to: 'fans#follow_artist'
      post 'unfollow', to: 'fans#unfollow_artist'
      get 'my_sales', to: 'artists#my_sales'
    end
    resources :products do
      member do
        post 'buy', to: 'orders#create'
      end
    end
  end

  resources :fans, only: [:show, :destroy] do
    member do
      get 'my_events'
      get 'followed_artists'
      get 'my_purchases', to: 'fan_purchases'
    end
  end

  root to: 'welcome#index'
end

app/models/product.rb
class Product < ApplicationRecord

  include Rails.application.routes.url_helpers

  belongs_to :artist
  has_many :orders
  has_many :photos, :dependent => :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true

  validates_associated :artist
  validates :title, presence: true, length: { maximum: 50 }
  validates :price, presence: true, length: { maximum: 10 }, numericality: { greater_than_or_equal_to: 0 }
  validates :stock, presence: true, length: { maximum: 10 }, numericality: { only_integer: true , greater_than_or_equal_to: 0 }

  scope :with_search_title, -> (search_title) {where ("title LIKE ?"), search_title}

  def to_s
    self.title
  end

  def base_uri
    artist_product_path(self.artist.name, self.id)
  end

  def report_stock
    return "#{self.stock} unidad/es disponibles" if self.in_stock?
    'Por el momento no se dispone de stock'
  end

  def in_stock?
    self.stock > 0
  end

  def stock_greater_or_equals_than?(aNumber)
    self.stock >= aNumber
  end

  def amount_of_sales
    self.orders.size
  end

  def update_stock_after_new_order(units_order)
    self.update(stock: self.stock - units_order)
  end

  def main_photo
    begin
      self.photos.first.image.url
    rescue
      return ActionController::Base.helpers.asset_path('default_product_photo.gif')
    end
  end

  def hash_data_for_order(units)
    { "id": self.id,
      "title": self.title,
      "quantity": units,
      "unit_price": self.price.to_f,
      "description": self.description,
      "currency_id":"ARS"
    }
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!
  before_action :authenticate_artist!, except: [:show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_artist

  # GET /artists/:artist_name/products
  def index
    @products = @artist.products
  end

  # GET /artists/:artist_name/products/1
  def show
    @photos = @product.photos
    @order = Order.new(product: @product, units: 0)
    @order.build_buyer
    @order.build_address
  end

  # GET /artists/:artist_name/products/new
  def new
    @product = Product.new
    @product.photos.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /artists/:artist_name/products
  def create
    @product = Product.new(product_params)
    @product.artist = @artist

    respond_to do |format|
      if @product.save
        create_photos
        format.html { redirect_to artist_products_path(@artist.name), notice: 'Product was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /artists/:artist_name/products/1
  def update
    respond_to do |format|
      if @product.update(product_params)
        update_photos
        format.html { redirect_to artist_products_path(@artist.name), notice: 'Product was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /artists/:artist_name/products/1
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to artist_products_path(@artist.name), notice: 'Product was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :stock, photos_attributes: [ ])
    end

    def create_photos
      photos = params[:product][:photos_attributes]
      if !photos.nil?
        photos.each_pair do |number_photo, photo|
           if !photo.nil?
             Photo.create(product: @product, image: photo["image"])
           end
        end
      end
    end

    def update_photos
      photos = params[:product][:photos_attributes]
      if !photos.nil?
        photos.each_pair do |number_photo, photo|
          # add new photo
          if !photo.nil? && !photo.has_key?("id")
            Photo.create(product: @product, image: photo["image"])
          end
          # update saved photo (change older by a new photo)
          if !photo.nil? && photo.has_key?("id") && photo.has_key?("image")
            Photo.destroy(photo["id"])
            Photo.create(product: @product, image: photo["image"])
          end
        end
      end
    end
end

app/views/products/_buyer_form.html.erb
<div class="modal fade" id="payment-modal" tabindex="-1" role="dialog" aria-labelledby="BuyerFormModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ingresa tus datos para la compra</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'layouts/form_aclaration' %>

        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-row">
          <div class="col-md-6 mb-3">
           <%= f.input :name, required: true, autofocus: true, placeholder: 'Carlos', input_html: { maxlength: 30, class: 'form-control' }, hint: 'El nombre que aparece en la tarjeta' %>
          </div>
          <div class="col-md-6 mb-3">
            <%= f.input :surname, placeholder: 'Perez', input_html: { maxlength: 30, class: 'form-control' }, hint: 'El apellido que aparece en la tarjeta' %>
          </div>
        </div>
        <div class="form-row">
          <div class="col-md-6 mb-3">
            <%= f.input :dni, as: :string, required: true, placeholder: '11555666', input_html: { maxlength: 8, class: 'form-control' }, hint: 'El DNI del titular de la tarjeta' %>
          </div>
          <div class="col-md-6 mb-3">
            <%= f.input :phone, placeholder: '0116548795', input_html: { maxlength: 13, class: 'form-control' }, hint: 'Ingresa el código de área seguido de tu número de teléfono sin el 15. Ej: 02215478745' %>
          </div>
        </div>


        <h4>Queres recibir el producto en tu casa?</h4>
        <button class="btn btn-success" id="withDelivery">Si</button>
        <%= f.simple_fields_for @order.address do |af| %>
          <div class="form-row">
            <div class="col-md-6 mb-3">
              <%= af.input :state, as: :select, label: 'Provincia', disabled: true, collection: CS.states(:AR).to_a, label_method: -> state {state[1]},
                           value_method: -> state {state[0]} , prompt: 'Selecciona tu provincia', input_html: { class: 'custom-select', id: 'state' } %>
            </div>
            <div class="col-md-6 mb-3">
              <%= af.input :city, as: :select, label: 'Localidad', disabled: true, prompt: 'Selecciona tu localidad', input_html: { class: 'custom-select', id: 'city' } %>
            </div>
          </div>
          <div class="form-row">
            <div class="col-md-3 mb-3">
              <%= af.input :street_name, placeholder: '25 de mayo', disabled: true, input_html: { class: 'form-control', maxlength: 25 } %>
            </div>
            <div class="col-md-3 mb-3">
              <%= af.input :street_number, placeholder: '222', disabled: true, input_html: { class: 'form-control', maxlength: 6 } %>
            </div>
            <div class="col-md-3 mb-3">
              <%= af.input :apartament, disabled: true, input_html: { class: 'form-control', maxlength: 5 } %>
            </div>
            <div class="col-md-3 mb-3">
              <%= af.input :zip, placeholder: '1896', disabled: true, input_html: { class: 'form-control', maxlength: 4 } %>
            </div>
          </div>

          <div class="checkbox">
            <label>
              <input type="checkbox" id="terms" data-error="Debe estar seguro de pagar!" required>
              Acepto los terminos y condiciones de "RedRock"
            </label>
            <div class="help-block with-errors">
            </div>
          </div>

          <div class="alert alert-info form-group ">
            Si tienes alguna duda puedes leer el <a href="#" class="alert-link">acuerdo legal</a> del sitio
          </div>

        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-primary" id="submitOrder">Pagar</button>
      </div>
    </div>
  </div>
</div>

app/views/products/_common_inputs.html.erb
<div class="form-inputs">
  <%= f.input :title, autofocus: true, placeholder: 'Ingresá el nombre o título del producto', input_html: { maxlength: 50 } %>
  <%= f.input :description, placeholder: 'Ingresá una descripción del producto. Especificá detalles del mismo' %>
  <%= f.input :price do %>
    <div class="input-group">
      <span class="input-group-prepend">
        <span class="input-group-text">$</span>
      </span>
      <%= f.input_field :price, min: 0, step: 0.1, class: 'form-control' %>
    </div>
  <% end %>
  <%= f.input :stock, placeholder: 'Ingresá la cantididad de unidades disponibles', input_html: { min: 0, step: 1 } %>

</div>

app/views/products/_products_list.html.erb
<ul class="list-group">
  <% if @products.empty? %>
    <h3>No hay productos disponibles por el momento</h3>
  <% end %>
  <% @products.each do |product| %>
    <li class="list-group-item justify-content-between">
      <div class="row">
        <div class="col-md-1">
          <% if not product.main_photo.nil? %>
            <%= image_tag(product.main_photo, size: '80x80') %>
          <% end %>
        </div>
        <div class="col-md-3">
          <%= link_to product.title, artist_product_path(product.artist.name, product), class: 'event-title' %>
        </div>
        <% if current_user.artist? %>
          <div class="col-md-1">
            <p>Stock: <%= product.stock %></p>
          </div>
          <div class="col-md-1">
            <p>Precio: $<%= product.price.round(2).to_s %></p>
          </div>
          <div class="col-md-2 offset-1">
            <%= link_to(icon('far', 'edit', 'Editar'), edit_artist_product_path(@artist, product), class: 'btn btn-success') %>
          </div>
          <div class="col-md-2">
            <%= link_to(icon('far', 'trash-alt', 'Eliminar'), artist_product_path(@artist,product), method: :delete,
                        class: 'btn btn-danger', data: { confirm: 'Desea eliminar el producto?' }) %>
          </div>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/products/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <h1>Editar producto</h1>

      <%= simple_form_for([@artist,@product], html: { multipart: true }, defaults: { input_html: { class: 'form-control' }}) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <%= render 'layouts/form_aclaration' %>

        <%= render partial: 'common_inputs', locals: { f: f } %>
        <%= f.simple_fields_for :photos do |photos_f| %>
          <label>Fotos</label>
          <div><small>La primera foto que cargues es la principal que tus seguidores pueden ver!</small></div>
          <ul class="photos-previewlist">
            <% i = 0
              @product.photos.each do |photo| %>
              <% if !photo.image.url.nil? %>
                <div class="photo-preview">
                  <%= link_to(icon('far', 'trash-alt'), photo_path(photo), { role: :button, method: :delete }) %>
                  <label for=<%= "photo-#{i}" %>>
                    <%= image_tag(photo.image.url, size:'80x80', id: "photo-preview-#{i}", onclick: 'openDialog(event)') %>
                  </label>
                  <%= photos_f.input_field :image, id: ("photo-#{i}".to_sym), name: "product[photos_attributes][#{i}][image]" , onchange: "displayProductPhoto(event)", value: photo.image %>
                  <% i+= 1 %>
                </div>
              <% end %>
            <% end %>
            <% (@product.max_photos_amount - @product.photos.size).times do %>
              <div class="photo-preview">
                <%=photos_f.label "photo-#{i}" do %>
                  <%= image_tag('add_photo_camera.png', id: "photo-preview-#{i}" ,size: '80x80', onclick: 'openDialog(event)') %>
                <% end %>
                <%= photos_f.input_field :image, id: ("photo-#{i}".to_sym), name: "product[photos_attributes][#{i}][image]" , onchange: "displayProductPhoto(event)" %>
                <% i+= 1 %>
              </div>
            <% end %>
          </ul>
        <% end %>

        <div class="form-actions">
          <%= f.submit 'Actualizar', class: 'btn btn-success' %>
          <%= link_to 'Cancelar', artist_products_path(@artist, @product), { class: 'btn btn-secondary', role: :button } %>
        </div>
      <% end %>

      </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <h2>Mis productos</h2>
      <%= link_to(icon('fas', 'compact-disc', 'Nuevo producto'), new_artist_product_path(@artist.name) , class: ['btn btn-success','new-button']) %>

      <%= render 'products_list' %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<%= stylesheet_link_tag params[:controller] %>
<% javascript_include_tag params[:controller] %>

<div class="container">
  <div class="row">
    <div class="col-md-12">

      <h1>Publicar producto</h1>

      <%= simple_form_for([@artist,@product], html: { multipart: true }, defaults: { input_html: { class: 'form-control' }}) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <%= render 'layouts/form_aclaration' %>

        <%= render partial: 'common_inputs', locals: { f: f } %>

        <%= f.simple_fields_for :photos do |photos_f| %>
          <label>Fotos</label>
          <div><small>La primera foto que cargues es la principal que tus seguidores pueden ver!</small></div>

            <ul class="photos-previewlist">
            <% @product.max_photos_amount.times do |i| %>
              <div class="photo-preview">
                <%=photos_f.label "photo-#{i}" do %>
                  <%= image_tag('add_photo_camera.png', id: "photo-preview-#{i}" ,size: '80x80', onclick: 'openDialog(event)') %>
                <% end %>
                <%= photos_f.input_field :image, id: ("photo-#{i}".to_sym), name: "product[photos_attributes][#{i}][image]" , onchange: "displayProductPhoto(event)" %>
              </div>
            <% end %>
          </ul>
        <% end %>

        <div class="form-actions">
          <%= f.submit 'Publicar', class: 'btn btn-success' %>
          <%= link_to 'Cancelar', artist_products_path(@artist, @product), { class: 'btn btn-secondary', role: :button } %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <!-- photos -->
      <div class="row">
        <% while !@photos.empty? do %>
          <% next_photos = @photos.first(3) %>
          <% next_photos.each do |photo| %>
            <div class="col-md-2 offset-1">
              <%= image_tag(photo.image.url, size:'150x150') unless photo.image.url.nil? %>
            </div>
          <% end %>
          <% @photos = @photos.drop(3) %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <h2><%= @product.title %></h2>
      <p id="without-stock"><%= @product.report_stock if current_user.profile == @product.artist %></p>

      <h1>$ <%= @product.price.round(2).to_s %></h1>
      <hr>
      <!-- form for order -->
      <%= render partial:'orders/order_form' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <h2>Descripci&oacuten del producto</h2>
      <p><em><%= @product.description %></em></p>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'product' %>