config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get 'signup/(:type)', to: 'user/registrations#new', as: 'signup'
  end

  devise_for :user, controllers: {registrations: 'user/registrations', sessions: 'user/sessions' },
             path_names: { edit: 'profile', sign_in: 'login', sign_out: 'logout' }

  get 'welcome/index'
  get 'search', to: 'welcome#search'
  get 'show_cities', to: 'welcome#show_cities'
  delete 'photos/:id', to: 'photos#destroy', as: 'photo'
  get 'register_pay' ,to: 'payments#create'

  resources :artists, param: :name, only: [:show, :destroy ] do
    resources :events do
      member do
        post 'add_event', to: 'fans#add_event', as: 'add'
        post 'remove_event', to: 'fans#remove_event', as: 'remove'
      end
    end
    member do
      post 'follow', to: 'fans#follow_artist'
      post 'unfollow', to: 'fans#unfollow_artist'
      get 'my_sales', to: 'artists#my_sales'
    end
    resources :products do
      member do
        post 'buy', to: 'orders#create'
      end
    end
  end

  resources :fans, only: [:show, :destroy] do
    member do
      get 'my_events'
      get 'followed_artists'
      get 'my_purchases', to: 'fan_purchases'
    end
  end

  root to: 'welcome#index'
end

app/views/layouts/_artist_menu.html.erb
<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Eventos">
  <%= link_to artist_events_path(current_user.profile.name), class: 'nav-link' do %>
    <%= icon('far', 'calendar-alt') %>
    <span class="nav-link-text">Mis eventos</span>
  <% end %>
</li>
<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Productos">
  <%= link_to artist_products_path(current_user.profile.name), class: 'nav-link' do %>
    <%= icon('fas', 'shopping-cart') %>
    <span class="nav-link-text">Mis productos</span>
  <% end %>
</li>
<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Ventas">
  <%= link_to my_sales_artist_path(current_user.profile.name), class: 'nav-link' do %>
    <%= icon('fas', 'balance-scale ') %>
    <span class="nav-link-text">Mis ventas</span>
  <% end %>
</li>

app/views/layouts/_fan_menu.html.erb
<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Eventos">
  <%= link_to my_events_fan_path(current_user.profile_id), class: 'nav-link' do %>
    <%= icon('far', 'calendar-alt') %>
    <span class="nav-link-text">Eventos</span>
  <% end %>
</li>
<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Artistas">
  <%= link_to followed_artists_fan_path(current_user.profile_id), class: 'nav-link' do %>
    <%= icon('fas', 'users') %>
    <span class="nav-link-text">Artistas</span>
  <% end %>
</li>
<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Compras">
  <%= link_to my_purchases_fan_path(current_user.profile_id), class: 'nav-link' do %>
    <%= icon('fas', 'balance-scale ') %>
    <span class="nav-link-text">Mis compras</span>
  <% end %>
</li>
<!--<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Events">
  <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
    <i class="fa fa-calendar"></i>
    <span class="nav-link-text">Mis eventos</span>
  </a>
  <ul class="sidenav-second-level collapse" id="collapseComponents">
    <li>
      <a href="navbar.html">Navbar</a>
    </li>
    <li>
      <a href="cards.html">Cards</a>
    </li>
  </ul>
</li> -->

app/views/layouts/_form_aclaration.html.erb
<small class="text-danger"><strong>Los campos marcados con * son obligatorios</strong></small>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <a class="navbar-brand" href="<%= root_path %>">RedRock</a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <%= render partial: 'layouts/user_menu' %>

    <ul class="navbar-nav ml-auto">
      <% if !user_signed_in? %>
        <li class="nav-item">
          <%= render partial: 'user/sessions/new' %>
        </li>
      <% else %>
        <li class="nav-item">
            <div class="input-group">
              <input type="text" name="model-search" id="model-search" placeholder="Buscar..." class="form-control"/>

              <span class="input-group-append">
                <%= button_tag class: 'btn btn-primary' do %>
                  <%= icon('fas', 'search') %>
                <% end %>
              </span>
            </div>
          <div><ul id="search-result"></ul></div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_navbar_notifications.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fa fa-fw fa-envelope"></i>
    <span class="d-lg-none">Messages
              <span class="badge badge-pill badge-primary">12 New</span>
            </span>
    <span class="indicator text-primary d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
  </a>
  <div class="dropdown-menu" aria-labelledby="messagesDropdown">
    <h6 class="dropdown-header">New Messages:</h6>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">
      <strong>David Miller</strong>
      <span class="small float-right text-muted">11:21 AM</span>
      <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
    </a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">
      <strong>Jane Smith</strong>
      <span class="small float-right text-muted">11:21 AM</span>
      <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
    </a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">
      <strong>John Doe</strong>
      <span class="small float-right text-muted">11:21 AM</span>
      <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
    </a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item small" href="#">View all messages</a>
  </div>
</li>
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fa fa-fw fa-bell"></i>
    <span class="d-lg-none">Alerts
              <span class="badge badge-pill badge-warning">6 New</span>
            </span>
    <span class="indicator text-warning d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
  </a>
  <div class="dropdown-menu" aria-labelledby="alertsDropdown">
    <h6 class="dropdown-header">New Alerts:</h6>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">
              <span class="text-success">
                <strong>
                  <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
              </span>
      <span class="small float-right text-muted">11:21 AM</span>
      <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
    </a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">
              <span class="text-danger">
                <strong>
                  <i class="fa fa-long-arrow-down fa-fw"></i>Status Update</strong>
              </span>
      <span class="small float-right text-muted">11:21 AM</span>
      <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
    </a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">
              <span class="text-success">
                <strong>
                  <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
              </span>
      <span class="small float-right text-muted">11:21 AM</span>
      <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
    </a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item small" href="#">View all alerts</a>
  </div>
</li>

app/views/layouts/_user_menu.html.erb
<% if user_signed_in? %>
  <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Perfil">
      <%= link_to edit_user_registration_path, class: 'nav-link' do %>
        <%= icon('far', 'user-circle') %>
        <span class="nav-link-text"><%= current_user.username %></span>
      <% end  %>
    </li>
    <% if current_user.artist? %>
      <%= render 'layouts/artist_menu' %>
    <% else %>
      <%= render 'layouts/fan_menu' %>
    <% end %>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Cerrar sesión">
      <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
        <%= icon('fas','sign-out-alt') %>
        <span class="nav-link-text">Cerrar sesi&oacuten</span>
      <% end %>
    </li>
  </ul>
  <ul class="navbar-nav sidenav-toggler">
    <li class="nav-item">
      <%= link_to(icon('far', 'angle-left'), :back, class:['nav-link', 'text-center'], id: 'sidenavToggler') %>
    </li>
  </ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>RockEnLasDiagonales</title>
    <meta name="description" content="Rock en las diagonales" />
    <meta name="keywords" lang="es" content="rock, La Plata, musica" >
    <meta http-equiv="Content-Type" content="text/html"; charset="UTF-8">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="fixed-nav sticky-footer" id="page-top">
    <%= render partial: 'layouts/navbar' %>
    <!--  <p class="notice"><% notice %></p>
      <p class="alert"><% alert %></p>
    -->
    <% if user_signed_in? %>
      <div class="content-wrapper">
        <div class="content-fluid">
          <%= yield %>
        </div>
      </div>
    <% else %>
      <%= yield %>
    <% end %>

  </body>
</html>